feat : Setup empty modules and workflow
anarahari/RickyMortyPoc pull request #1
Opened 2024-11-12 12:03 UTC by anarahari

Empty modules have been setup 
data
domain
presentation
common

2024-11-12 13:09 UTC, shreyansh-mm requested changes
Let's add a workflow which will do lint checks and run all the unit tests for you on every PR.

2024-11-12 13:09 UTC, shreyansh-mm commented on .idea/gradle.xml
This file should be in `.gitignore`, it should not be in VCS

2024-11-12 13:09 UTC, shreyansh-mm commented on app/build.gradle.kts
> +    //alias(libs.plugins.ksp)
Let's uncomment it or remove it.

2024-11-12 14:42 UTC, shubhamsinghmutualmobile commented on common/build.gradle.kts
> +    //ksp(libs.dagger.compiler)
Same here (let's remove all unused code)

2024-11-12 14:42 UTC, shubhamsinghmutualmobile commented on data/build.gradle.kts
> +    //ksp(libs.dagger.compiler)
Same

2024-11-12 14:42 UTC, shubhamsinghmutualmobile commented on domain/build.gradle.kts
> +    //ksp(libs.dagger.compiler)
Same

2024-11-12 14:42 UTC, shubhamsinghmutualmobile commented on presentation/build.gradle.kts
> +    //ksp(libs.dagger.compiler)
Same

2024-11-12 14:47 UTC, anarahari commented
> Let's add a workflow which will do lint checks and run all the unit tests for you on every PR.

added the same

2024-11-13 18:07 UTC, shreyansh-mm approved these changes

2024-11-14 05:56 UTC, merged