Feature screen three domain
anarahari/RickyMortyPoc pull request #10
Opened 2024-12-04 11:28 UTC by anarahari

- Created EpisodeRepository interface to get episode details

- Created GetEpisodeDetailsUseCase to fetch the episode details response from repository

- Added unit test cases for GetEpisodeDetailsUseCase to fetch episode details on success and failure scenarios.

- Added characters variable to Episode model to fetch list of characters.

- Changes for lintchecks

2024-12-05 10:59 UTC, shreyansh-mm requested changes

2024-12-05 10:59 UTC, shreyansh-mm commented on app/src/main/java/com/compose/rickymortypoc/MainActivity.kt
> +//                    )[CharacterViewModel::class.java]
Remove the commented code

2024-12-05 10:59 UTC, shreyansh-mm commented on data/src/main/java/com/compose/data/datamapper/DataMapper.kt
> +fun mapToOriginModel(origin: GetCharacterDetailsQuery.Origin?): Origin {
private

2024-12-05 10:59 UTC, shreyansh-mm commented on data/src/main/java/com/compose/data/datamapper/DataMapper.kt
> +fun mapToLocationModel(location: GetCharacterDetailsQuery.Location?): Location {
private

2024-12-05 10:59 UTC, shreyansh-mm commented on data/src/main/java/com/compose/data/datamapper/DataMapper.kt
> +fun mapToEpisodeModel(episodes: List<GetCharacterDetailsQuery.Episode?>?): List<Episode>? {
private

2024-12-05 10:59 UTC, shreyansh-mm commented on data/src/main/java/com/compose/data/repository/CharacterRepositoryImpl.kt
> +        }
Exception should not be consumed, it should be propagated forward.
So we can show appropriate error to use.

2024-12-05 10:59 UTC, shreyansh-mm commented on domain/src/test/java/com/compose/domain/usecase/GetCharacterDetailsUseCaseTest.kt
> +        Dispatchers.setMain(testDispatcher)
Test should work fine without this line

2024-12-05 10:59 UTC, shreyansh-mm commented on domain/src/test/java/com/compose/domain/usecase/GetCharacterDetailsUseCaseTest.kt
> +        Dispatchers.resetMain()
this should also be not needed

2024-12-05 10:59 UTC, shreyansh-mm commented on presentation/src/main/java/com/compose/presentation/screens/CharacterDetailsScreen.kt
> +fun CharacterDetailsItems(
private

2024-12-05 10:59 UTC, shreyansh-mm commented on presentation/src/main/java/com/compose/presentation/screens/CharacterDetailsScreen.kt
> +fun DisplayCharacterDetailsData(
private

2024-12-05 10:59 UTC, shreyansh-mm commented on presentation/src/main/java/com/compose/presentation/screens/CharacterDetailsScreen.kt
> +                modifier = Modifier
You don't need to pass empty modifier

2024-12-05 10:59 UTC, shreyansh-mm commented on presentation/src/main/java/com/compose/presentation/screens/CharacterDetailsScreen.kt
> +    Column(modifier.verticalScroll(rememberScrollState())) {
let's move `rememberScrollState()` to a variable

2024-12-05 10:59 UTC, shreyansh-mm commented on presentation/src/main/java/com/compose/presentation/screens/CharacterDetailsScreen.kt
> +        Spacer(modifier.padding(top = MaterialTheme.dimens.paddingExtraLarge))
Modifier coming from args should only apply to parent composable.

2024-12-05 10:59 UTC, shreyansh-mm commented on presentation/src/main/java/com/compose/presentation/screens/CharacterDetailsScreen.kt
> +            color = Color.Black,
This should come from `MaterialTheme`

2024-12-05 10:59 UTC, shreyansh-mm commented on presentation/src/main/java/com/compose/presentation/screens/CharacterDetailsScreen.kt
> +            modifier = modifier.padding(start = MaterialTheme.dimens.paddingExtraLarge)
New modifier should be used

2024-12-05 10:59 UTC, shreyansh-mm commented on presentation/src/main/java/com/compose/presentation/screens/CharacterDetailsScreen.kt
> +        CharacterStatus(modifier, character)
This modifier should not be passed forward

2024-12-05 10:59 UTC, shreyansh-mm commented on presentation/src/main/java/com/compose/presentation/screens/CharacterDetailsScreen.kt
> +fun CharacterStatus(modifier: Modifier, character: Character) {
private

2024-12-05 10:59 UTC, shreyansh-mm commented on presentation/src/main/java/com/compose/presentation/screens/CharacterDetailsScreen.kt
> +            color = Color.Black
all these values can come from `textStyle` / `typography`

2024-12-05 10:59 UTC, shreyansh-mm commented on presentation/src/main/java/com/compose/presentation/screens/FirstScreen.kt
> +    }
our UI layer needs to be as dumb as possible, this logic should not sit here

2024-12-06 11:53 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/compose/presentation/screens/CharacterDetailsScreen.kt
> +private fun CharacterStatus(modifier: Modifier = Modifier, character: Character) {
This composable should only ask for the `status` variable

2024-12-06 11:53 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/compose/presentation/screens/CharacterDetailsScreen.kt
> +private fun CharacterSpecies(modifier: Modifier, character: Character) {
This composable should only ask for the `species` variable

2024-12-06 11:53 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/compose/presentation/screens/CharacterDetailsScreen.kt
> +private fun CharacterGender(modifier: Modifier, character: Character) {
This composable should only ask for the `gender` variable

2024-12-06 11:53 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/compose/presentation/screens/CharacterDetailsScreen.kt
> +private fun CharacterOrigin(modifier: Modifier, character: Character) {
This composable should only ask for the `origin` variable

2024-12-06 11:53 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/compose/presentation/screens/CharacterDetailsScreen.kt
> +private fun CharacterLocation(modifier: Modifier, character: Character) {
This composable should only ask for the `location` variable

2024-12-06 11:53 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/compose/presentation/screens/CharacterDetailsScreen.kt
> +private fun DisplayEpisodes(modifier: Modifier, character: Character) {
This composable should only ask for the `episodes` variable

2024-12-06 11:53 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/compose/presentation/screens/CharacterDetailsScreen.kt
> +                EpisodesItem(modifier, episode = character.episodes?.get(index)!!)
Avoid using the double bang operator (`!!`) whenever you can

2024-12-06 11:54 UTC, shubhamsinghmutualmobile approved these changes

2024-12-06 12:55 UTC, merged