Feat/feature screen one domain
anarahari/RickyMortyPoc pull request #2
Opened 2024-11-13 17:45 UTC by anarahari

2024-11-15 05:38 UTC, shreyansh-mm requested changes

2024-11-15 05:38 UTC, shreyansh-mm commented on .idea/compiler.xml
This file should not be committed to VCS

2024-11-15 05:38 UTC, shreyansh-mm commented on .idea/gradle.xml
This file should not be committed to VCS

2024-11-15 05:38 UTC, shreyansh-mm commented on .idea/graphql-settings.xml
This file should not be committed to VCS

2024-11-15 05:38 UTC, shreyansh-mm commented on .idea/misc.xml
This file should not be committed to VCS

2024-11-15 05:38 UTC, shreyansh-mm commented on domain/src/main/java/com/compose/domain/paging/CharacterPagingSource.kt
> +class CharacterPagingSource(
This should not be in domain

2024-11-15 05:38 UTC, shreyansh-mm commented on domain/src/main/java/com/compose/domain/repository/CharacterRepository.kt
> +    suspend fun getCharacters(): Flow<PagingData<GetCharactersQuery.Result>>
we should not be returning `GetCharactersQuery.Result`, we need to create our own model and map the response to our class using mapper/extension functions

2024-11-15 10:53 UTC, anarahari commented on domain/src/main/java/com/compose/domain/paging/CharacterPagingSource.kt
> +class CharacterPagingSource(
done
moved it to data module

2024-11-15 10:59 UTC, anarahari commented on .idea/compiler.xml
done

2024-11-15 10:59 UTC, anarahari commented on .idea/gradle.xml
done

2024-11-15 10:59 UTC, anarahari commented on .idea/graphql-settings.xml
done

2024-11-15 10:59 UTC, anarahari commented on .idea/misc.xml
done

2024-11-19 14:25 UTC, shreyansh-mm requested changes

2024-11-19 14:25 UTC, shreyansh-mm commented on domain/src/main/java/com/compose/domain/usecase/GetCharactersUseCase.kt
> +    suspend fun getCharacters(): Flow<List<CharacterModel>> {
Methods of usecase are always called `invoke`

2024-11-19 14:25 UTC, shreyansh-mm commented on domain/src/main/java/com/compose/domain/mapper/CharacterModel.kt
> +    var status: String
Should be `val` not `var`

2024-11-21 12:10 UTC, merged