Feat/feature screenone data module
anarahari/RickyMortyPoc pull request #3
Opened 2024-11-14 14:18 UTC by anarahari

2024-11-15 05:38 UTC, shreyansh-mm requested changes

2024-11-15 05:38 UTC, shreyansh-mm commented on common/src/main/java/com/compose/common/CommonConstants.kt
> +object CommonConstants {
Should be marked as internal

2024-11-15 05:38 UTC, shreyansh-mm commented on data/src/main/java/com/compose/data/repository/CharacterRepositoryImpl.kt
> +class CharacterRepositoryImpl @Inject constructor(private val apolloClient: ApolloClient) : CharacterRepository {
Let's see if we can make this class `internal`

2024-11-15 11:15 UTC, anarahari commented on data/src/main/java/com/compose/data/repository/CharacterRepositoryImpl.kt
> +class CharacterRepositoryImpl @Inject constructor(private val apolloClient: ApolloClient) : CharacterRepository {
ok let me try

2024-11-15 12:15 UTC, anarahari commented on common/src/main/java/com/compose/common/CommonConstants.kt
> +object CommonConstants {
done

2024-11-19 14:31 UTC, shreyansh-mm requested changes

2024-11-19 14:31 UTC, shreyansh-mm commented on data/src/main/java/com/compose/data/datamapper/DataMapper.kt
> +        status = results?.character?.status.orEmpty()
why do we have or empty?

2024-11-19 14:31 UTC, shreyansh-mm commented on data/src/main/java/com/compose/data/paging/CharacterPagingSource.kt
> +                    }*/
This is being confusing to read, lets not keep code commented, remove them so it becomes easier to read.

2024-11-19 14:31 UTC, shreyansh-mm commented on data/src/main/java/com/compose/data/repository/CharacterRepositoryImpl.kt
> +            return@flow
I don't think we need to use this, we can update the conditions above and make our code cleaner

2024-11-20 06:35 UTC, anarahari commented on data/src/main/java/com/compose/data/datamapper/DataMapper.kt
> +        status = results?.character?.status.orEmpty()
orEmpty method checks if the string value is null, if the value is null, an empty string is returned

2024-11-21 11:08 UTC, merged