Feature screen two presentation
anarahari/RickyMortyPoc pull request #8
Opened 2024-11-27 17:15 UTC by anarahari

feat : Feature screen two presentation

- Composable functions to display Character Details Screen starting with Image, Character details, Location, Origin and Episodes

- First Screen : Added LaunchedEffect for api call to get characters

- First Screen - Added navigation to character details on click of list item

-  Custom App Bar : dynamic title

- Dimens.Kt file to display custom sizes of text, paddings

- CharacterModel : Added Location model 

- Passed GetCharacterDetailsUseCase as a parameter to viewmodelprovider

- DataMapper : Added location model mapper

- Lintcheck changes

2024-11-28 14:12 UTC, shubhamsinghmutualmobile requested changes

2024-11-28 14:12 UTC, shubhamsinghmutualmobile commented on common/src/main/graphql/GetCharacterDetails.graphql
> +        }
The design requires you to fetch only the `name` and `dimension` values

2024-11-28 14:12 UTC, shubhamsinghmutualmobile commented on common/src/main/graphql/GetCharacterDetails.graphql
> +        }
The design requires you to fetch only the `id` (optional) and `name` values

2024-11-28 14:12 UTC, shubhamsinghmutualmobile commented on data/src/main/java/com/compose/data/datamapper/DataMapper.kt
> +}
Using double bang operator (`!!`) should be avoided whenever possible. Kotlin recommends to embrace nullable types instead. We can also get rid of the `orEmpty` extension here and delegate using this extension to the composable/view itself.

2024-11-28 14:12 UTC, shubhamsinghmutualmobile commented on data/src/main/java/com/compose/data/datamapper/DataMapper.kt
> +}
Make sure to get rid of `orEmpty` from all other models as well. I might not add the same comment over and over on all models.

2024-11-28 14:12 UTC, shubhamsinghmutualmobile commented on data/src/main/java/com/compose/data/datamapper/DataMapper.kt
> +    return list
Use `episodes?.map` instead. Creating a new list is relatively memory-inefficient.

2024-11-28 14:12 UTC, shubhamsinghmutualmobile commented on data/src/main/java/com/compose/data/module/DataModule.kt
> +    @Singleton
Try to be mindful of when to create `singleton` instances. Singletons should only be created when using factory instances is considerably costlier in terms of time and/or memory.

2024-11-28 14:12 UTC, shubhamsinghmutualmobile commented on data/src/main/java/com/compose/data/module/DataModule.kt
> +    @Singleton
A usecase is generally a very small class and hence should not need to be created as a singleton. Also, why do we need a `coroutineDispatcher` inside a usecase? 🤔

2024-11-28 14:12 UTC, shubhamsinghmutualmobile commented on data/src/main/java/com/compose/data/repository/CharacterRepositoryImpl.kt
> +            results
This can be shortened by removing `val results =`

2024-11-28 14:12 UTC, shubhamsinghmutualmobile commented on data/src/main/java/com/compose/data/repository/CharacterRepositoryImpl.kt
> +        }
If the return type of this function is nullable (i.e. `CharacterModel?`), then why are we passing a model instance from the `catch` block? Wouldn't it be more suitable to pass `null` from it?

2024-11-28 14:12 UTC, shubhamsinghmutualmobile commented on domain/src/main/java/com/compose/domain/mapper/CharacterModel.kt
> +data class EpisodeModel(
Nit: Removing the `Model` suffix would make the classes more readable.

> [!NOTE]
> `Nit` is short for `nitpick`, meaning that implementing this comment is `optional`.

2024-11-28 14:12 UTC, shubhamsinghmutualmobile commented on domain/src/main/java/com/compose/domain/usecase/GetCharacterDetailsUseCase.kt
> +    @IoDispatcher private val coroutineDispatcher: CoroutineDispatcher
No need for the dispatcher. The task of selecting which thread/dispatcher to use should be delegated to the presentation layer instead (which in our case would be the `ViewModel` class).

2024-11-28 14:12 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/compose/presentation/navigation/RMNavGraph.kt
> +                }
Nit: This can be shortened down to `onBackButtonPressed = navController::navigateUp`

2024-11-28 14:12 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/compose/presentation/screens/CharacterDetailsScreen.kt
> +fun DisplayData(
Try using more descriptive composable/function names. `DisplayData` doesn't tell us a lot about what it does.

2024-11-28 14:12 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/compose/presentation/screens/CharacterDetailsScreen.kt
> +fun CharacterScreenLoadData(
Try using more descriptive composable/function names. `CharacterScreenLoadData` doesn't tell us a lot about what it does.

2024-11-28 14:12 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/compose/presentation/screens/CharacterDetailsScreen.kt
> +fun CharacterStatus(characterModel: CharacterModel, modifier: Modifier) {
There are some general conventions we should use while creating composables. Like: `Modifier should be the first param of a composable.`

Try using a composable lint like [compose-lints](https://slackhq.github.io/compose-lints/) to help yourself.

2024-11-28 14:12 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/compose/presentation/screens/CharacterDetailsScreen.kt
> +            top = MaterialTheme.dimens.padding8dp
Creating variables with exact `dp` names is not maintainable in long term. Let's say right now its value is `padding20Dp = 20.dp`, but tomorrow the designer updates it to `24.dp`, so wouldn't having `padding20Dp = 24.dp` be a little misleading?

2024-11-28 14:12 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/compose/presentation/screens/CharacterDetailsScreen.kt
> +            top = MaterialTheme.dimens.padding8dp
Try using more generic names like `paddingExtraSmall`, `paddingSmall`, `paddngMedium`, `paddingLarge`, `paddingExtraLarge`, etc.

2024-11-28 14:12 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/compose/presentation/screens/FirstScreen.kt
> +    }
Writing network calls inside a Composable should be avoided first of all. I understand since the alternatives are more complex, therefore, to keep things simple for now, let's introduce a flag named `areCharactersFetched` in this composable that persists configuration changes and allows you to ensure that you don't make unnecessary network calls on every configuration change.

You can write the following:
```kotlin
@Composable
fun CharacterListScreen() {
   var areCharactersFetched by rememberSaveable { mutableStateOf(false) }
   
   LaunchedEffect(Unit) {
       if (!areCharactersFetched) {
           // Updating the state before making the network call to avoid the scenario where
           // the configuration is changed before the network call is finished executing
           isDataFetched = true
           viewModel.getCharacters()
       }
   }
   
   // Rest of your code
}
```

2024-11-28 14:12 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/compose/presentation/screens/FirstScreen.kt
> +        items(characterList.size, key = { characterList[it].id!! }) { index ->
Using the double bang operator (`!!`) should be avoided wherever possible

2024-11-28 14:12 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/compose/presentation/screens/FirstScreen.kt
> +                onNavigateCharacterDetails(character.id ?: "")
Write `character.id.orEmpty()` instead

2024-11-28 14:12 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/compose/presentation/ui/theme/Dimens.kt
> +)
As mentioned before, try using generic names like `small`, `medium`, `large` to make these classes more maintainable in long term.

2024-11-28 14:12 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/compose/presentation/ui/theme/Dimens.kt
> +val LocalDimens = compositionLocalOf<Dimens> { error("No dimens provided") }
Why are we not providing the `RMDimens` in this line? Providing values using `CompositionLocalProvider` should only be necessary when instantiating the object requires something that can only be provided from a Composable scope (like Context).

2024-11-28 14:12 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/compose/presentation/ui/theme/Theme.kt
> +            CompositionLocalProvider(LocalDimens provides RMDimens) {
As mentioned before, no need for this `CompositionLocalProvider` here.

2024-11-28 14:12 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/compose/presentation/viewmodel/CharacterViewModel.kt
> +//    }
Remove unused code

2024-11-28 14:13 UTC, shubhamsinghmutualmobile commented
@anarahari This PR was too large to review 😅 Please avoid creating large PRs from now on. Try to limit them to 150-200 LOC for now.

2024-12-02 13:03 UTC, anarahari commented on domain/src/main/java/com/compose/domain/usecase/GetCharacterDetailsUseCase.kt
> +    @IoDispatcher private val coroutineDispatcher: CoroutineDispatcher
So are you saying that there is no need to specify flowOn and pass the dispatcher ?

2024-12-06 12:55 UTC, merged